#!/bin/bash

RUN_DIR=/var/vcap/sys/run/blobstore
LOG_DIR=/var/vcap/sys/log/blobstore
PIDFILE=$RUN_DIR/nginx.pid

DATA=/var/vcap/store/shared
TMP_DIR=$DATA/tmp/uploads

source /var/vcap/packages/capi_utils/pid_utils.sh

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $DATA
    mkdir -p $TMP_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR $DATA

    pid_guard "${PIDFILE}" "blobstore_nginx"
    echo $$ > "${PIDFILE}"

    exec /var/vcap/packages/nginx_webdav/sbin/nginx -c /var/vcap/jobs/blobstore/config/nginx.conf >>$LOG_DIR/nginx.stdout.log 2>>$LOG_DIR/nginx.stderr.log
    ;;

  stop)
    timeout=1
    sigkill_on_timeout=0
    kill_and_wait "${PIDFILE}" "${timeout}" "${sigkill_on_timeout}"
    ;;

  *)
    echo "Usage: nginx_ctl {start|stop}"
    ;;
esac
exit 0
