#!/usr/bin/env bash

set -ex

#This script is used to help compare the number of rows between two given mysql databases.
#Operators need to provide username, password, hostname, and database name in that order 
#for the first database, followed by the same information for the second database.

before_db_user=$1
before_db_pw=$2
before_db_hostname=$3
before_db_name=$4

after_db_user=$5
after_db_pw=$6
after_db_hostname=$7
after_db_name=$8

function count_rows () {
  mysql -u "$1" --password="$2" --host="$3" "$4" -e "select table_name, table_rows from information_schema.tables where table_schema = '$4';"
}

count_rows $before_db_user $before_db_pw $before_db_hostname $before_db_name > before_count
count_rows $after_db_user $after_db_pw $after_db_hostname $after_db_name > after_count

diff before_count after_count
