#!/bin/bash

set -exu

# create and upload a release
pushd ~/workspace/capi-release
  bosh sync-blobs
  bosh create-release --force --name capi
  bosh upload-release --rebase
popd

# deploy to current bosh env
bosh deploy ~/workspace/cf-deployment/cf-deployment.yml \
  -v system_domain=$BOSH_LITE_DOMAIN \
  -o ~/workspace/capi-ci/cf-deployment-operations/use-latest-stemcell.yml \
  -o ~/workspace/capi-ci/cf-deployment-operations/skip-cert-verify.yml \
  -o ~/workspace/cf-deployment/operations/bosh-lite.yml \
  -o ~/workspace/cf-deployment/operations/bypass-cc-bridge.yml \
  -o ~/workspace/capi-ci/cf-deployment-operations/use-latest-capi.yml $@
