#!/bin/bash
set -exu

# create and upload a release
pushd ~/workspace/capi-release
  bosh sync-blobs
  bosh update-cloud-config --non-interactive ~/workspace/cf-deployment/bosh-lite/cloud-config.yml
  bosh create-release --force --name capi
  bosh upload-release --rebase
popd
