#!/bin/bash
set -eu

ask_to_update_cloud_config=ask
while getopts hny opt ; do
    case "$opt" in
	n) ask_to_update_cloud_config=no ;;
	y) ask_to_update_cloud_config=yes ;;
	h) echo "\
Usage: $(basename $0) [-n -- don't update bosh-lite cloud-config]
                         [-y -- always update bosh-lite cloud-config
                         (default is to ask)]" ; exit 1;;
    esac
done

# create and upload a release
pushd ~/workspace/capi-release
  bosh sync-blobs
  set +x
  if [[ "${ask_to_update_cloud_config}" == ask ]] ; then
      echo -n "Update cloud-config (don't do this for aws/gcp environments)? [N/y] "
      read x
      x1=$(echo $x | tr '[:upper:]' '[:lower:]')
      case $x1 in
	  y|yes) ask_to_update_cloud_config=yes ;;
      esac
  fi
  if [[ "${ask_to_update_cloud_config}" == yes ]] ; then
      bosh update-cloud-config --non-interactive ~/workspace/cf-deployment/bosh-lite/cloud-config.yml
  fi
  set -x
  bosh create-release --force --name capi
  bosh upload-release --rebase
popd
