#!/usr/bin/env bash

if [[ -z $1 ]]; then
  echo "Usage: install-git-hooks <git-hook-repo-path>"
  exit 1
fi

GIT_HOOK_PATH=$1
PRE_PUSH=${GIT_HOOK_PATH}/pre-push

if [ ! -f ${PRE_PUSH} ]; then
  echo "#!/bin/bash" > ${PRE_PUSH}
  chmod +x ${PRE_PUSH}
fi

if grep -q 'git-hooks/pre-push' ${PRE_PUSH}; then
  echo "pre-push already installed."
else
  echo >> ${PRE_PUSH}
  echo './git-hooks/pre-push' >> ${PRE_PUSH}
  echo "pre-push installed."
fi
