#!/bin/bash

set -e

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    cd packages/${bosh_pkg}

    {
      cat spec | grep -v '# gosub'

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [ -d "../../src/${repo}/Godeps/_workspace/src/${package}" ]; then
          package="${repo}/Godeps/_workspace/src/${package}"
        fi
        echo ${package} | sed -e 's|\(.*\)|  - capi-release\/src/\1\/*.go # gosub|g'
        if ls ../../src/${package}/*.s >/dev/null 2>&1; then
          echo ${package} | sed -e 's|\(.*\)|  - capi-release\/src/\1\/*.s # gosub|g'
        fi
      done
    } > spec.new

    mv spec.new spec
  )
}

sync_package cc_uploader             -app  github.com/cloudfoundry-incubator/cc-uploader/cmd/cc-uploader &
sync_package stager                  -app  github.com/cloudfoundry-incubator/stager/cmd/stager &

sync_package nsync                   -app  github.com/cloudfoundry-incubator/nsync/cmd/nsync-bulker \
  -app github.com/cloudfoundry-incubator/nsync/cmd/nsync-listener &

sync_package tps                     -app  github.com/cloudfoundry-incubator/tps/cmd/tps-listener \
  -app github.com/cloudfoundry-incubator/tps/cmd/tps-watcher &

wait

git diff --name-only packages/*/spec
