#!/usr/bin/env bash

set -ue

get_uaa_admin_password() {
  echo "Getting UAA admin password from credhub... "
  credhub login -s "$CREDHUB_SERVER" -u "$CREDHUB_CLIENT" -p "$CREDHUB_SECRET" --skip-tls-validation
  uaa_admin_password=$(credhub get --name '/bosh-lite/cf/uaa_admin_client_secret' --output-json | jq -r '.value')
}

login() {
  uaac target uaa.${BOSH_LITE_DOMAIN} --skip-ssl-validation
  uaac token client get admin -s $uaa_admin_password
}

main() {
  get_uaa_admin_password
  login
}

main
